name: chitose
version: 1.0.1
description: >-
  Chitose is a package that makes it easy to handle Dart Lists, which are implemented inspired by Programming Haskell.
homepage: https://github.com/akira08280/chitose
documentation:
environment:
  sdk: '>=2.13.0 <3.0.0'
dev_dependencies: 
  lints: ^1.0.1
  test: ^1.17.10
dependencies: 
  collection: ^1.15.0
